### ISSUE TITLE
App crash during playing - macOS HighSierra

### ISSUE THREAD

**Issue by r21gh** [filipuic/playme#18]
Application has been crashed during playing. 
macOS High Sierra
PlayMe v1.0.3

`Uncaught Exception: Error: Object has been destroyed at WebContents.executeJavaScript (/Applications/PlayMe.app/Contents/Resources/electron.asar/browser/api/web-contents.js:191:30) at PlaybackActions.playPause (/Applications/PlayMe.app/Contents/Resources/app.asar/src/main/PlaybackActions.js:8:20) at Function.globalShortcut.register (/Applications/PlayMe.app/Contents/Resources/app.asar/src/main/Shortcuts.js:6:23)`

**Comment by filipnbc** [comment]
Thank you for reporting that!
does that happen every time? are there any steps to reproduce or anything specific you could remember that was related to the crash?

**Comment by r21gh** [comment]
I could not reproduce the mentioned bug scenario, but I have seen this one today after updating to mac os Mojave.

This is the scenario for another similar error (today, mac os 10.14 Mojave)
1 - open the app 
2 - Without play anything, minimize the app
3 - Try to open the app from top menu
4 - error !
`Uncaught Exception:
Error: Object has been destroyed
    at AppActions.showWindow (/Applications/PlayMe.app/Contents/Resources/app.asar/src/main/AppActions.js:8:23)
    at click (/Applications/PlayMe.app/Contents/Resources/app.asar/src/main/TrayMenu.js:51:18)
    at MenuItem.click (/Applications/PlayMe.app/Contents/Resources/electron.asar/browser/api/menu-item.js:55:9)
    at Function.executeCommand (/Applications/PlayMe.app/Contents/Resources/electron.asar/browser/api/menu.js:29:13)`


it's good to now that after opening the app, a pop up (Security & Privacy, Accessibility)claimed that play me wants to control my computer and I refused to allow.
It means without the permission it will crash.
I changed the permission and it worked.
